# Copyright (c) 2019-2022, see AUTHORS. Licensed under MIT License, see LICENSE.
# Modified for fakechroot with Android glibc support

{ config, writeScript, writeText }:

let
  inherit (config.build) installationDir;

  # Paths for fakechroot login
  androidGlibc = config.build.androidGlibc or null;
  androidFakechroot = config.build.androidFakechroot or null;
  bashInteractive = config.build.bashInteractive or null;
in

writeScript "login" ''
  #!/system/bin/sh
  # This file is generated by Nix-on-Droid with fakechroot support. DO NOT EDIT.
  set -eu

  export USER="${config.user.userName}"
  export HOME="${config.user.home}"

  # Debug hook: source user script if it exists (for debugging/overrides)
  # Create ~/.config/nix-on-droid/login-debug.sh to customize login behavior
  DEBUG_SCRIPT="${config.user.home}/.config/nix-on-droid/login-debug.sh"
  if [ -f "$DEBUG_SCRIPT" ]; then
    . "$DEBUG_SCRIPT"
  fi

  # Install pending login-inner if not in use
  if test -e ${installationDir}/usr/lib/.login-inner.new; then
    echo "Installing new login-inner..."
    /system/bin/mv ${installationDir}/usr/lib/.login-inner.new ${installationDir}/usr/lib/login-inner
  fi

  # Fakechroot configuration
  # Android paths are now hardcoded into libfakechroot.so at compile time.
  # We only need to set FAKECHROOT_BASE for path translation.
  # Note: /nix/store path translation is built into ld.so (dl-android-paths.h)
  STORE="${installationDir}/nix/store"
  GLIBC_LIB="$STORE/${baseNameOf androidGlibc}/lib"
  LD_LINUX="$GLIBC_LIB/ld-linux-aarch64.so.1"
  BASH_BIN="$STORE/${baseNameOf bashInteractive}/bin/bash"
  FAKECHROOT_LIB="$STORE/${baseNameOf androidFakechroot}/lib/fakechroot/libfakechroot.so"
  LOGIN_INNER="${installationDir}/usr/lib/login-inner"

  # Verify critical files exist
  for _file in "$LD_LINUX" "$BASH_BIN" "$FAKECHROOT_LIB" "$LOGIN_INNER"; do
    if [ ! -e "$_file" ]; then
      echo "Error: Required file not found: $_file" >&2
      exit 1
    fi
  done

  # Execute using Android glibc's ld.so
  # NOTE: We use /system/bin/env to explicitly pass environment variables because
  # Android's /system/bin/sh doesn't properly pass exported variables to exec'd processes.
  #
  # All FAKECHROOT_* settings (ELFLOADER, LIBRARY_PATH, PRELOAD, BASE, EXCLUDE_PATH)
  # are now hardcoded into libfakechroot.so at compile time.
  # Only FAKECHROOT=true is needed to enable fakechroot mode.
  exec /system/bin/env \
    USER="$USER" \
    HOME="$HOME" \
    FAKECHROOT="true" \
    "$LD_LINUX" \
      --argv0 "$BASH_BIN" \
      --library-path "$GLIBC_LIB" \
      --preload "$FAKECHROOT_LIB" \
      "$BASH_BIN" "$LOGIN_INNER" "$@"
''
